os: Visual Studio 2019
branches:
  only:
    - master

environment:
  RUST_BACKTRACE: 1

install:
  - ps: |
      Invoke-WebRequest https://github.com/dokan-dev/dokany/releases/download/v1.3.1.1000/DokanSetup_redist.exe -OutFile "$Env:TEMP\DokanSetup.exe"
      Start-Process "$Env:TEMP\DokanSetup.exe" -ArgumentList "/quiet /norestart" -Wait
  - ps: Invoke-WebRequest https://win.rustup.rs/x86_64 -OutFile "$Env:TEMP\rustup-init.exe"
  - cmd: "\"%TEMP%\\rustup-init.exe\" -y --default-host x86_64-pc-windows-msvc"
  - ps: $Env:PATH = "$Env:PATH;C:\Users\appveyor\.cargo\bin"

before_build:
  - ps: Update-AppveyorBuild -Version (git describe --all --long).Split("/")[1]
  - cmd: git submodule update --init

build_script:
  - cmd: cargo test --release --workspace --no-run
  - cmd: cargo doc --release --workspace

test_script:
  - cmd: cargo test --release --workspace
  - cmd: cargo test --release --workspace -- --ignored
