os: Visual Studio 2019
branches:
  only:
    - master

environment:
  RUST_BACKTRACE: 1
  AccessTokenDokanDoc:
    secure: bWAI+3DIqfNZT/llXhEGiAsmSzJAmywFVyNgwHaTA5afb24GdHEQid6dRN5VJiTm

install:
  - ps: |
      Invoke-WebRequest https://github.com/dokan-dev/dokany/releases/download/v1.3.1.1000/DokanSetup_redist.exe -OutFile "$Env:TEMP\DokanSetup.exe"
      Start-Process "$Env:TEMP\DokanSetup.exe" -ArgumentList "/quiet /norestart" -Wait
  - ps: Invoke-WebRequest https://win.rustup.rs/x86_64 -OutFile "$Env:TEMP\rustup-init.exe"
  - cmd: "\"%TEMP%\\rustup-init.exe\" -y --default-host x86_64-pc-windows-msvc"
  - ps: $Env:PATH = "$Env:PATH;C:\Users\appveyor\.cargo\bin"

before_build:
  - ps: Update-AppveyorBuild -Version (git describe --all --long).Split("/")[1]
  - cmd: git submodule update --init

build_script:
  - cmd: cargo test --release --workspace --no-run
  - cmd: cargo doc --release --workspace

test_script:
  - cmd: cargo test --release --workspace
  - cmd: cargo test --release --workspace -- --ignored

on_success:
    - ps: |
          if ("$env:APPVEYOR_PULL_REQUEST_TITLE" -or "$env:APPVEYOR_REPO_BRANCH" -ne "master") {
            return;
          }

          # Update documentation
          cd $env:APPVEYOR_BUILD_FOLDER
          git config --global user.email "appveyor@appveyor.org"
          git config --global user.name "appveyor"
          git.exe clone -b gh-pages --single-branch  https://lirynastark:$($env:AccessTokenDokanDoc)@github.com/dokan-dev/dokan-rust-doc.git doc
          New-Item -ItemType Directory $env:APPVEYOR_BUILD_FOLDER\doc\html | Out-Null
          Copy-Item $env:APPVEYOR_BUILD_FOLDER\target\doc\* -Destination $env:APPVEYOR_BUILD_FOLDER\doc\html\ -Recurse
          cd $env:APPVEYOR_BUILD_FOLDER\doc\html\
          if ($(git status --porcelain)) {
            Write-Host "Update documentation..." -ForegroundColor Green
            git add -A
            Write-Host "All changes ready to commit" -ForegroundColor Green
            git commit -m "Latest documentation on successful appveyor build $env:APPVEYOR_BUILD_VERSION auto-pushed to gh-pages"
            Write-Host "Push changes..." -ForegroundColor Green
            git push -f origin gh-pages
            Write-Host "Pushed. Documentation updated!" -ForegroundColor Green
          } else {
            Write-Host "No documentation changes detected." -ForegroundColor Green
          }
