os: Visual Studio 2019
branches:
  only:
    - master

environment:
  RUST_BACKTRACE: 1
  AccessTokenDokanDoc:
    secure: bWAI+3DIqfNZT/llXhEGiAsmSzJAmywFVyNgwHaTA5afb24GdHEQid6dRN5VJiTm
  matrix:
    - ARCH: x86_64
      UPLOAD_DOC: "true"
    - ARCH: x86_64
      USE_INSTALLED_LIB: "true"
    - ARCH: i686
    - ARCH: i686
      USE_INSTALLED_LIB: "true"

install:
  - ps: |
      Invoke-WebRequest https://github.com/dokan-dev/dokany/releases/download/v1.3.1.1000/DokanSetup_redist.exe -OutFile "$Env:TEMP\DokanSetup.exe"
      Start-Process "$Env:TEMP\DokanSetup.exe" -ArgumentList "/quiet /norestart" -Wait
  - ps: Invoke-WebRequest https://win.rustup.rs/x86_64 -OutFile "$Env:TEMP\rustup-init.exe"
  - cmd: "\"%TEMP%\\rustup-init.exe\" -y --default-host %ARCH%-pc-windows-msvc"
  - ps: $Env:PATH = "$Env:PATH;C:\Users\appveyor\.cargo\bin"
  - ps: |
      if ($Env:USE_INSTALLED_LIB -eq $true) {
          $Env:DokanLibrary1_LibraryPath_x64 = "C:\Program Files\Dokan\Dokan Library-1.3.1\lib\"
          $Env:DokanLibrary1_LibraryPath_x86 = "C:\Program Files\Dokan\Dokan Library-1.3.1\x86\lib\"
      }

before_build:
  - ps: $version = (git describe --all --long).Split("/")[1]
  - ps: Update-AppveyorBuild -Version $version
  - cmd: git submodule update --init

build_script:
  - cmd: cargo test --release --workspace --no-run
  - cmd: cargo doc --release --workspace

test_script:
  - cmd: cargo test --release --workspace
  - cmd: cargo test --release --workspace -- --ignored

deploy_script:
  - ps: |
      $ErrorActionPreference = "Stop"
      if ($Env:APPVEYOR_REPO_TAG -ne $true -or $Env:UPLOAD_DOC -ne $true) {
          return;
      }
      git config --global user.email appveyor@appveyor.org
      git config --global user.name appveyor
      cmd /c "git clone https://lirynastark:$($Env:AccessTokenDokanDoc)@github.com/dokan-dev/dokan-rust-doc.git doc 2>&1"
      if ($LASTEXITCODE -ne 0) { $host.SetShouldExit($LASTEXITCODE) }
      if (Test-Path doc\html) {
          Remove-Item -Recurse -Force doc\html\*
      } else {
          mkdir doc\html
      }
      Copy-Item -Recurse target\doc\* doc\html\
      cd doc
      if ($(git status --porcelain)) {
          Write-Host "Updating documentation..." -ForegroundColor Green
          git add -A
          git commit -m "Automatically update documentation for $version"
          cmd /c "git push 2>&1"
          if ($LASTEXITCODE -ne 0) { $host.SetShouldExit($LASTEXITCODE) }
          Write-Host -ForegroundColor Green "Documentation updated!"
      } else {
          Write-Host -ForegroundColor Green "No documentation changes detected."
      }
